#!/bin/sh
### BEGIN INIT INFO
# Provides:          display-lcd
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop servod.
# Description:       This script starts/stops servod.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

res=0

case "$1" in
  start)
	sudo killall dispd > /dev/null 2>&1
	sudo /usr/local/sbin/dispd > /dev/null 2>&1 &
	;;
  restart|reload|force-reload)
	sudo killall dispd > /dev/null 2>&1
	sudo /usr/local/sbin/dispd > /dev/null 2>&1 &
	;;
  stop)
	sudo killall dispd > /dev/null 2>&1
	;;
  *)
	echo "Usage: display-lcd [start|stop]"
	res=3
	;;
esac

exit $res

